### ISSUE TITLE
missing spartan3 scala library

### ISSUE THREAD

**Issue by 2015mp** [tomverbeure/panologic-g2#11]
make syn ends up with an error that spartan3 is missing (Log below).   Temp workaround was to create a directory called spartan3, and copy the dcm primitive from spartan6 (and change package to spartan3).  I assume the actual spartan3 primitives for g1 are missing.

C:\Work\Panologic\g2\panologic-g2\spinal>make syn
sbt "run-main pano.PanoVerilog"
Java HotSpot(TM) Client VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading project definition from C:\Work\Panologic\g2\panologic-g2\spinal\project
[info] Loading project definition from C:\Users\Owner\.sbt\0.13\staging\12ca90deb9f3a32624be\vexriscv\project
[info] Set current project to panologic-g2 (in build file:/C:/Work/Panologic/g2/panologic-g2/spinal/)
[info] Compiling 29 Scala sources to C:\Work\Panologic\g2\panologic-g2\spinal\target\scala-2.11\classes...
[error] C:\Work\Panologic\g2\panologic-g2\spinal\src\main\scala\pano-g1\PanoG1.scala:9: not found: object spartan3
[error] import spartan3._
[error]        ^
[error] one error found
[error] (root/compile:compileIncremental) Compilation failed
[error] Total time: 18 s, completed Feb 2, 2019 1:33:43 AM
make: *** [syn]

**Comment by bzboi** [comment]
I confirm I'm seeing the same thing. Looks like it was a side effect of Jan 23, 2019 commit to add G1 support. Build ulpi branch instead. What's the goal of having the G1 files in master branch? ISE 14.7 WEBPACK doesn't support LX150 and ISE 14.7 (Win 10) doesn't support Spartan3.

**Comment by tomverbeure** [comment]
I'll have a look at this.

Tom

**Comment by tomverbeure** [comment]
I've simply removed the reference to the Spartan 3 library.

The reason why G1 and G2 are in the same tree is because Skip and I are working on both the G1 and G2 and want to share as much as possible.

Tom
