### ISSUE TITLE
generic JTAG adapter and openocd?

### ISSUE THREAD

**Issue by fanoush** [tomverbeure/panologic-g2#12]
Hello,

I don't know where to ask, sorry if this is the wrong place. Just ordered G1 and G2 from ebay and googled a bit and I am not sure. Can I use some generic JTAG adapter to transfer bitstream to FPGA ? 

Does your blog post https://tomverbeure.github.io/2019/09/15/Loading-a-Spartan-6-bitstream-with-openocd.html apply to spartan 3 or 6 in G1/G2 too?   Also found another blog post here https://catleytech.com/?p=2679 so it looks like it could indeed work so is there some catch  like different jtag voltage levels or the closed tool for this FPGA producing different file format not usable from openocd?

BTW is there some place to discuss G1/G2?  e.g some gitter.im room?

EDIT:
Oh the blog post points to https://github.com/quartiq/bscan_spi_bitstreams with spi flashing bitstreams and there are ones named bscan_spi_xc6slx100.bit and bscan_spi_xc6slx150.bit so looks like all pieces of the puzzle are there (?)

**Comment by tomverbeure** [comment]
Hello Fanoush,

> Does your blog post https://tomverbeure.github.io/2019/09/15/Loading-a-Spartan-6-bitstream-with-openocd.html apply to spartan 3 or 6 in G1/G2 too?

I don't think I've tried it yet with my G2 board, but I don't see why it wouldn't work.

I have successfully flashed G1s, but I still haven't tried with a G2. Skip Hansen has been able to make it work over Ethernet, of course: https://github.com/skiphansen/pano_progfpga.

Tom

**Comment by tomverbeure** [comment]
I created a Pano Logic gitter chat room: https://gitter.im/panologic/community.
