### ISSUE TITLE
Any info on the inter-board connector?

### ISSUE THREAD

**Issue by yomboprime** [tomverbeure/panologic-g2#3]
It should be nice to have spare I/O. Are there any free pins left on the connector? They could be "extracted" with a custom pcb I think.

**Comment by tomverbeure** [comment]
The smaller half of that connector carries most of the Chrontel inputs to generate DVI. Those are only about 17 pins or so (data is DDR). 

So it’s a bit of a mystery why there are so many other pins.

I haven’t mapped them out and it pretty low priority, but I doubt that there will be something useful for GPIOs.

**Comment by yomboprime** [comment]
Thanks.

**Comment by derekmulcahy** [comment]
Here is a link to a breakout board for the connector.

https://github.com/twj42/PanoLogicG2_ReverseEngineering/blob/master/pages/bob.md

Quite a nice design. 16 FPGA pins instead of micro-HDMI, LEDs and the switch.

**Comment by tomverbeure** [comment]
> Here is a link to a breakout board for the connector.
> 
> https://github.com/twj42/PanoLogicG2_ReverseEngineering/blob/master/pages/bob.md
> 
> Quite a nice design. 16 FPGA pins instead of micro-HDMI, LEDs and the switch.

Wow, that's awesome!
