### ISSUE TITLE
RAM amount on G2 devices

### ISSUE THREAD

**Issue by zephray** [tomverbeure/panologic-g2#4]
Mine is G2 Rev.C, it has 2 D9LPX RAM chip on it, which is 2 x MT47H32M16. I believe each chip is 512Mb in 32M x 16bits configuration, which is 64 MBytes, and two chips add up to 128 MBytes instead of 256 MBytes.

**Comment by tomverbeure** [comment]
I mistakenly converted 512mbit to 128Mbyte instead of 64Mbyte. So the G2 rev.B and rev.C have the same amount of memory.

Fixed with commit bd78ec57d4efaa4d3134.

Thanks for letting me know!
